### ISSUE TITLE
Error: no parsers registered for: "] - A"

### ISSUE THREAD

**Issue by KevinInc50** [webextensions/live-css-editor#146]
Error: no parsers registered for: "] - A"
    at parse (C:\Users\kevin\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\snapdragon\lib\parser.js:473:15)
    at Parser.parse (C:\Users\kevin\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\snapdragon\lib\parser.js:477:24)
    at Snapdragon.parse (C:\Users\kevin\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\snapdragon\index.js:122:28)
    at Snapdragon.<anonymous> (C:\Users\kevin\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\lib\braces.js:40:45)
    at Braces.parse (C:\Users\kevin\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\lib\braces.js:66:26)
    at Braces.expand (C:\Users\kevin\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\lib\braces.js:87:18)
    at create (C:\Users\kevin\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\index.js:142:15)
    at memoize (C:\Users\kevin\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\index.js:298:13)
    at braces.create (C:\Users\kevin\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\index.js:165:10)
    at braces.expand (C:\Users\kevin\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\index.js:81:17)

^^^^ Error ^^^^

**Comment by webextensions** [comment]
@KevinInc50 
Can you elaborate a little more about the steps to reproduce this issue?

**Comment by KevinInc50** [comment]
all I did was run the install command, when I get home I can try to
recreate it and send you the logs

**Comment by Kurou-kun** [comment]
in folder you are trying to start the server there are files/folder with incorrect formatting.
