### ISSUE TITLE
Error: no parsers registered for: "] Spo"

### ISSUE THREAD

**Issue by MichaelGatuma** [webextensions/live-css-editor#50]
```To list the files being watched, run live-css with --list-files parameter or "list-files" configuration.
Adding files to watch  ..................................................................................................
Error: no parsers registered for: "] Spo"
    at parse (C:\Users\USER\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\snapdragon\lib\parser.js:473:15)
    at Parser.parse (C:\Users\USER\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\snapdragon\lib\parser.js:477:24)
    at Snapdragon.parse (C:\Users\USER\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\snapdragon\index.js:122:28)
    at Snapdragon.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\lib\braces.js:40:45)
    at Braces.parse (C:\Users\USER\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\lib\braces.js:66:26)
    at Braces.expand (C:\Users\USER\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\lib\braces.js:87:18)
    at create (C:\Users\USER\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\index.js:142:15)
    at memoize (C:\Users\USER\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\index.js:298:13)
    at Function.braces.create (C:\Users\USER\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\index.js:165:10)
    at Function.braces.expand (C:\Users\USER\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\index.js:81:17)

^^^^ Error ^^^^```

**Comment by webextensions** [comment]
@MichaelGatuma 
Can you provide steps to reproduce the bug?

Also, see if the solution in https://github.com/webextensions/live-css-editor/issues/47 also applies to your situation.

**Comment by webextensions** [comment]
Marking this issue Closed due to inactivity.
