### ISSUE TITLE
Error: no parsers registered for: "] Edu"

### ISSUE THREAD

**Issue by anleyn** [webextensions/live-css-editor#89]
Hi! I have an error:

```
live-css server version: 8.0.3
...
Use live-css server along with the browser extension "Live editor for CSS, Less & Sass - Magic CSS":
    https://github.com/webextensions/live-css-editor

Adding files to watch ..
Error: no parsers registered for: "] Edu"
    at parse (D:\Users\Anley\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\snapdragon\lib\parser.js:473:15)
    at Parser.parse (D:\Users\Anley\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\snapdragon\lib\parser.js:477:24)
    at Snapdragon.parse (D:\Users\Anley\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\snapdragon\index.js:122:28)
    at Snapdragon.<anonymous> (D:\Users\Anley\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\lib\braces.js:40:45)
    at Braces.parse (D:\Users\Anley\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\lib\braces.js:66:26)
    at Braces.expand (D:\Users\Anley\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\lib\braces.js:87:18)
    at create (D:\Users\Anley\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\index.js:142:15)
    at memoize (D:\Users\Anley\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\index.js:298:13)
    at Function.braces.create (D:\Users\Anley\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\index.js:165:10)
    at Function.braces.expand (D:\Users\Anley\AppData\Roaming\npm\node_modules\@webextensions\live-css\node_modules\braces\index.js:81:17)

^^^^ Error ^^^^
Sorry! live-css server encountered an unexpected error!
```

**Comment by webextensions** [comment]
@anleyn 
Can you run it with the `--debug` parameter for the command like:
```sh
$ live-css --debug
```
and provide the logs here.
